#!/bin/bash

# Colors
green='\033[0;32m'
red='\033[0;31m'
nocolor='\033[0m'

set -e

SOURCE_ABI_PATH=$PWD/contracts/artifacts/contracts/payment/MCPayment.sol

# Check if `contracts` repository exists
if [ ! -d "contracts" ]; then
	echo -e "${red}Contracts directory does not exist.${nocolor}"
	exit 1
fi

# Check if jq exists
which jq 1>/dev/null || exit 1

pushd $PWD/contracts > /dev/null

# Print warning if current branch is not up to date with the remote branch. Only for master branch.
current_branch=$(git branch --show-current)
if [ "$current_branch" == "master" ]; then
	git fetch
	if git status -uno | grep "Your branch is up to date" > /dev/null ; then
		echo -e \
		"${green}Your branch '$current_branch' is up to date with the remote branch.${nocolor}"
	else
		echo -e \
		"${red}Your branch '$current_branch' is not up to date with the remote branch.\n\
Please sync your branch with the remote branch.${nocolor}"
	fi
fi

npm i
npm run compile
popd > /dev/null

touch $PWD/contracts-abi/abi.json $PWD/contracts-abi/bytecode $PWD/contracts-abi/multi-chain-payment/go/abi/abi.go

cat $SOURCE_ABI_PATH/MCPayment.json | jq .abi > $PWD/contracts-abi/abi.json
cat $SOURCE_ABI_PATH/MCPayment.json | jq .bytecode > $PWD/contracts-abi/bytecode
docker run \
	-v $PWD/contracts-abi/abi.json:/abi.json:ro \
	-v $PWD/contracts-abi/bytecode:/bytecode:ro \
	-v $PWD/contracts-abi/multi-chain-payment/go/abi/abi.go:/abi.go \
	--rm --name ethereum-node \
	ethereum/client-go:alltools-v1.14.12 \
	abigen --abi=/abi.json --pkg=abi \
	--out=abi.go --type="MCPayment"



