/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniversalVerifier } from "./UniversalVerifier";
export * as factories from "./factories";
export { UniversalVerifier__factory } from "./factories/UniversalVerifier__factory";
