name: Publish npm onchain non merklized issuer to NPM

on: workflow_dispatch
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.IDENTITY_NPM_PUBLISH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: onchain-non-merklized-issuer-base/v0/js
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm publish
